/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRESENTACION;

/**
 *
 * @author Surface
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupEsDocente = new javax.swing.ButtonGroup();
        jInternalFrameAltaUsr = new javax.swing.JInternalFrame();
        jTextFieldNombreUsuario = new javax.swing.JTextField();
        jTextFieldApellUsuario = new javax.swing.JTextField();
        jLabelNomUsu = new javax.swing.JLabel();
        jLabelApellUsr = new javax.swing.JLabel();
        jSpinnerNacDiaUsr = new javax.swing.JSpinner();
        jSpinnerNacMesUsr = new javax.swing.JSpinner();
        jSpinnerNacAnioUsr = new javax.swing.JSpinner();
        jLabelFechNacUsr = new javax.swing.JLabel();
        jTextFieldEmailUsr = new javax.swing.JTextField();
        jLabelEmailUsr = new javax.swing.JLabel();
        jTextFieldNickUsr = new javax.swing.JTextField();
        jLabelNickUsr = new javax.swing.JLabel();
        jLabelDocente = new javax.swing.JLabel();
        jRadioButtonSiDocente = new javax.swing.JRadioButton();
        jRadioButtonNoDocente = new javax.swing.JRadioButton();
        jComboBoxDocInstituto = new javax.swing.JComboBox<>();
        jLabel1DocInst = new javax.swing.JLabel();
        jButtonConfAlta = new javax.swing.JButton();
        jButtonCancAlta = new javax.swing.JButton();
        jInternalFrameModUsr = new javax.swing.JInternalFrame();
        jComboBoxListaUsr = new javax.swing.JComboBox<>();
        jLabelNickModUsr = new javax.swing.JLabel();
        jTextFieldModUsrNom = new javax.swing.JTextField();
        jTextFieldModUsrAp = new javax.swing.JTextField();
        jTextFieldModUsrEmail = new javax.swing.JTextField();
        jLabelModUsrNom = new javax.swing.JLabel();
        jLabelModUsrAp = new javax.swing.JLabel();
        jLabelModUsrEmail = new javax.swing.JLabel();
        jSpinnerModUsrDiaNc = new javax.swing.JSpinner();
        jSpinnerModUsrMesNac = new javax.swing.JSpinner();
        jSpinnerModUsrAnioNac = new javax.swing.JSpinner();
        jLabelModUsrNac = new javax.swing.JLabel();
        jButtonConfModUsr = new javax.swing.JButton();
        jButtonCancModUsr = new javax.swing.JButton();
        jInternalFrameConsUsr = new javax.swing.JInternalFrame();
        jComboBoxConsUsrList = new javax.swing.JComboBox<>();
        jLabelConsUsrNick = new javax.swing.JLabel();
        jTextFieldConsUsrNom = new javax.swing.JTextField();
        jLabel1ConsUsrNom = new javax.swing.JLabel();
        jTextFieldConsUsrAp = new javax.swing.JTextField();
        jLabelConsUsrAp = new javax.swing.JLabel();
        jTextFieldConsUsrEmail = new javax.swing.JTextField();
        jLabelConsUsrEmail = new javax.swing.JLabel();
        jTextFieldConsUsrFechNac = new javax.swing.JTextField();
        jLabelConsUsrFechNac = new javax.swing.JLabel();
        jComboBoxConsUsrProg = new javax.swing.JComboBox<>();
        jComboBoxConsUsrCursos = new javax.swing.JComboBox<>();
        jComboBoxConsUsrEd = new javax.swing.JComboBox<>();
        jLabelConsUsrProg = new javax.swing.JLabel();
        jLabelConsUsrCurso = new javax.swing.JLabel();
        jLabelConsUsrEd = new javax.swing.JLabel();
        jButtonConUsrSalir = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuItemAltaUsuario = new javax.swing.JMenuItem();
        jMenuItemConsultaUsuario = new javax.swing.JMenuItem();
        jMenuItemModUsuario = new javax.swing.JMenuItem();
        jMenuCursos = new javax.swing.JMenu();
        jMenuItemAltaCurso = new javax.swing.JMenuItem();
        jMenuItemConsultaCurso = new javax.swing.JMenuItem();
        jMenuItemAltaEdCurso = new javax.swing.JMenuItem();
        jMenuItemConsEdCurso = new javax.swing.JMenuItem();
        jMenuItemInscEdCurso = new javax.swing.JMenuItem();
        jMenuProgramas = new javax.swing.JMenu();
        jMenuItemCrearPrograma = new javax.swing.JMenuItem();
        jMenuItemAddCursoProg = new javax.swing.JMenuItem();
        jMenuItemConsProg = new javax.swing.JMenuItem();
        jMenuInstitutos = new javax.swing.JMenu();
        jMenuItemAltaInst = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Administrador");
        setBounds(250,250,500,650);
        setLocation(new java.awt.Point(30, 0));
        setMaximizedBounds(new java.awt.Rectangle(300, 300, 500, 850));
        setName("ventanaPrincipal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 850));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 850));
        getContentPane().setLayout(null);

        jInternalFrameAltaUsr.setTitle("Alta Usuario");
        jInternalFrameAltaUsr.setVisible(false);

        jLabelNomUsu.setText("Nombre:");

        jLabelApellUsr.setText("Apellido:");

        jSpinnerNacDiaUsr.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jSpinnerNacMesUsr.setModel(new javax.swing.SpinnerNumberModel(12, 1, 12, 1));

        jSpinnerNacAnioUsr.setModel(new javax.swing.SpinnerNumberModel(2000, 1920, 2020, 1));

        jLabelFechNacUsr.setText("Fecha de Nac.:");

        jLabelEmailUsr.setText("Email:");

        jLabelNickUsr.setText("Nickname:");

        jLabelDocente.setText("Docente:");

        buttonGroupEsDocente.add(jRadioButtonSiDocente);
        jRadioButtonSiDocente.setText("Si");
        jRadioButtonSiDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSiDocenteActionPerformed(evt);
            }
        });

        buttonGroupEsDocente.add(jRadioButtonNoDocente);
        jRadioButtonNoDocente.setSelected(true);
        jRadioButtonNoDocente.setText("No");
        jRadioButtonNoDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNoDocenteActionPerformed(evt);
            }
        });

        jComboBoxDocInstituto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxDocInstituto.setEnabled(false);

        jLabel1DocInst.setText("Instituto:");

        jButtonConfAlta.setText("Confirmar ");

        jButtonCancAlta.setText("Cancelar");
        jButtonCancAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameAltaUsrLayout = new javax.swing.GroupLayout(jInternalFrameAltaUsr.getContentPane());
        jInternalFrameAltaUsr.getContentPane().setLayout(jInternalFrameAltaUsrLayout);
        jInternalFrameAltaUsrLayout.setHorizontalGroup(
            jInternalFrameAltaUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameAltaUsrLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jInternalFrameAltaUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDocente)
                    .addComponent(jLabelEmailUsr)
                    .addGroup(jInternalFrameAltaUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelNomUsu)
                        .addComponent(jLabelApellUsr)
                        .addComponent(jLabelFechNacUsr, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabelNickUsr)
                    .addComponent(jLabel1DocInst))
                .addGroup(jInternalFrameAltaUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameAltaUsrLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jInternalFrameAltaUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldApellUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameAltaUsrLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jInternalFrameAltaUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jInternalFrameAltaUsrLayout.createSequentialGroup()
                                .addComponent(jButtonConfAlta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCancAlta))
                            .addComponent(jComboBoxDocInstituto, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jInternalFrameAltaUsrLayout.createSequentialGroup()
                                .addComponent(jRadioButtonSiDocente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonNoDocente))
                            .addGroup(jInternalFrameAltaUsrLayout.createSequentialGroup()
                                .addComponent(jSpinnerNacDiaUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerNacMesUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerNacAnioUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldEmailUsr)
                            .addComponent(jTextFieldNickUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46))
        );
        jInternalFrameAltaUsrLayout.setVerticalGroup(
            jInternalFrameAltaUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameAltaUsrLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jInternalFrameAltaUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomUsu)
                    .addComponent(jTextFieldNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jInternalFrameAltaUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellUsr)
                    .addComponent(jTextFieldApellUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jInternalFrameAltaUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerNacDiaUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerNacMesUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerNacAnioUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechNacUsr))
                .addGap(39, 39, 39)
                .addGroup(jInternalFrameAltaUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmailUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmailUsr))
                .addGap(39, 39, 39)
                .addGroup(jInternalFrameAltaUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNickUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNickUsr))
                .addGap(46, 46, 46)
                .addGroup(jInternalFrameAltaUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDocente)
                    .addComponent(jRadioButtonSiDocente)
                    .addComponent(jRadioButtonNoDocente))
                .addGap(35, 35, 35)
                .addGroup(jInternalFrameAltaUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDocInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1DocInst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jInternalFrameAltaUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfAlta)
                    .addComponent(jButtonCancAlta))
                .addGap(31, 31, 31))
        );

        getContentPane().add(jInternalFrameAltaUsr);
        jInternalFrameAltaUsr.setBounds(40, 40, 410, 550);

        jInternalFrameModUsr.setTitle("Modificar datos del usuario");
        jInternalFrameModUsr.setVisible(false);

        jComboBoxListaUsr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelNickModUsr.setText("Nickname:");

        jTextFieldModUsrEmail.setEnabled(false);

        jLabelModUsrNom.setText("Nombre:");

        jLabelModUsrAp.setText("Apellido:");

        jLabelModUsrEmail.setText("Email:");

        jSpinnerModUsrDiaNc.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jSpinnerModUsrMesNac.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        jSpinnerModUsrAnioNac.setModel(new javax.swing.SpinnerNumberModel(1920, 1920, 2020, 1));

        jLabelModUsrNac.setText("Fecha de Nac:");

        jButtonConfModUsr.setText("Confirmar");

        jButtonCancModUsr.setText("Cancelar");
        jButtonCancModUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancModUsrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameModUsrLayout = new javax.swing.GroupLayout(jInternalFrameModUsr.getContentPane());
        jInternalFrameModUsr.getContentPane().setLayout(jInternalFrameModUsrLayout);
        jInternalFrameModUsrLayout.setHorizontalGroup(
            jInternalFrameModUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameModUsrLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jInternalFrameModUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameModUsrLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonConfModUsr)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancModUsr))
                    .addGroup(jInternalFrameModUsrLayout.createSequentialGroup()
                        .addGroup(jInternalFrameModUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNickModUsr)
                            .addComponent(jLabelModUsrNom)
                            .addComponent(jLabelModUsrAp)
                            .addComponent(jLabelModUsrEmail)
                            .addComponent(jLabelModUsrNac))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jInternalFrameModUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jInternalFrameModUsrLayout.createSequentialGroup()
                                .addComponent(jSpinnerModUsrDiaNc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerModUsrMesNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpinnerModUsrAnioNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldModUsrEmail)
                            .addComponent(jTextFieldModUsrAp)
                            .addComponent(jTextFieldModUsrNom)
                            .addComponent(jComboBoxListaUsr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(40, 40, 40))
        );
        jInternalFrameModUsrLayout.setVerticalGroup(
            jInternalFrameModUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameModUsrLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jInternalFrameModUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrameModUsrLayout.createSequentialGroup()
                        .addGroup(jInternalFrameModUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInternalFrameModUsrLayout.createSequentialGroup()
                                .addGroup(jInternalFrameModUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelNickModUsr)
                                    .addComponent(jComboBoxListaUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62)
                                .addComponent(jTextFieldModUsrNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelModUsrNom))
                        .addGap(40, 40, 40)
                        .addComponent(jTextFieldModUsrAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelModUsrAp))
                .addGap(42, 42, 42)
                .addGroup(jInternalFrameModUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldModUsrEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelModUsrEmail))
                .addGap(44, 44, 44)
                .addGroup(jInternalFrameModUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerModUsrDiaNc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerModUsrMesNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerModUsrAnioNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelModUsrNac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jInternalFrameModUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfModUsr)
                    .addComponent(jButtonCancModUsr))
                .addGap(60, 60, 60))
        );

        getContentPane().add(jInternalFrameModUsr);
        jInternalFrameModUsr.setBounds(40, 30, 420, 560);

        jInternalFrameConsUsr.setTitle("Consulta usuario");
        jInternalFrameConsUsr.setVisible(false);

        jComboBoxConsUsrList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelConsUsrNick.setText("Nickname:");

        jTextFieldConsUsrNom.setEnabled(false);

        jLabel1ConsUsrNom.setText("Nombre:");

        jTextFieldConsUsrAp.setEnabled(false);

        jLabelConsUsrAp.setText("Apellido:");

        jTextFieldConsUsrEmail.setEnabled(false);

        jLabelConsUsrEmail.setText("Email:");

        jTextFieldConsUsrFechNac.setEnabled(false);

        jLabelConsUsrFechNac.setText("Fecha de Nac.:");

        jComboBoxConsUsrProg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxConsUsrCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxConsUsrEd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelConsUsrProg.setText("Programas:");

        jLabelConsUsrCurso.setText("Cursos:");

        jLabelConsUsrEd.setText("Ediciones:");

        jButtonConUsrSalir.setText("Salir");
        jButtonConUsrSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConUsrSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameConsUsrLayout = new javax.swing.GroupLayout(jInternalFrameConsUsr.getContentPane());
        jInternalFrameConsUsr.getContentPane().setLayout(jInternalFrameConsUsrLayout);
        jInternalFrameConsUsrLayout.setHorizontalGroup(
            jInternalFrameConsUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameConsUsrLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jInternalFrameConsUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonConUsrSalir)
                    .addGroup(jInternalFrameConsUsrLayout.createSequentialGroup()
                        .addGroup(jInternalFrameConsUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelConsUsrNick, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1ConsUsrNom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelConsUsrEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelConsUsrFechNac, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelConsUsrAp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelConsUsrProg, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelConsUsrCurso, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelConsUsrEd, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(52, 52, 52)
                        .addGroup(jInternalFrameConsUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldConsUsrNom)
                            .addComponent(jComboBoxConsUsrList, 0, 193, Short.MAX_VALUE)
                            .addComponent(jTextFieldConsUsrEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldConsUsrFechNac, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldConsUsrAp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxConsUsrProg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxConsUsrCursos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxConsUsrEd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(44, 44, 44))
        );
        jInternalFrameConsUsrLayout.setVerticalGroup(
            jInternalFrameConsUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameConsUsrLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jInternalFrameConsUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrameConsUsrLayout.createSequentialGroup()
                        .addGroup(jInternalFrameConsUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInternalFrameConsUsrLayout.createSequentialGroup()
                                .addGroup(jInternalFrameConsUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jInternalFrameConsUsrLayout.createSequentialGroup()
                                        .addGroup(jInternalFrameConsUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelConsUsrNick)
                                            .addComponent(jComboBoxConsUsrList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jInternalFrameConsUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldConsUsrNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1ConsUsrNom))
                                        .addGap(18, 18, 18)
                                        .addGroup(jInternalFrameConsUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextFieldConsUsrAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelConsUsrAp))
                                        .addGap(18, 18, 18)
                                        .addGroup(jInternalFrameConsUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldConsUsrEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelConsUsrEmail))
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldConsUsrFechNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelConsUsrFechNac))
                                .addGap(56, 56, 56)
                                .addComponent(jComboBoxConsUsrProg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelConsUsrProg))
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxConsUsrCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelConsUsrCurso))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameConsUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxConsUsrEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConsUsrEd))
                .addGap(49, 49, 49)
                .addComponent(jButtonConUsrSalir)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        getContentPane().add(jInternalFrameConsUsr);
        jInternalFrameConsUsr.setBounds(0, 0, 396, 562);

        jMenuUsuarios.setText("Usuarios");

        jMenuItemAltaUsuario.setText("Alta usuario");
        jMenuItemAltaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAltaUsuarioActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemAltaUsuario);

        jMenuItemConsultaUsuario.setText("Consulta de usuario");
        jMenuItemConsultaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaUsuarioActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemConsultaUsuario);

        jMenuItemModUsuario.setText("Modificar datos");
        jMenuItemModUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModUsuarioActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemModUsuario);

        jMenuBar2.add(jMenuUsuarios);

        jMenuCursos.setText("Cursos");

        jMenuItemAltaCurso.setText("Alta curso");
        jMenuCursos.add(jMenuItemAltaCurso);

        jMenuItemConsultaCurso.setText("Consulta de curso");
        jMenuCursos.add(jMenuItemConsultaCurso);

        jMenuItemAltaEdCurso.setText("Alta edición");
        jMenuCursos.add(jMenuItemAltaEdCurso);

        jMenuItemConsEdCurso.setText("Consulta edición");
        jMenuCursos.add(jMenuItemConsEdCurso);

        jMenuItemInscEdCurso.setText("Inscripcion a edición");
        jMenuCursos.add(jMenuItemInscEdCurso);

        jMenuBar2.add(jMenuCursos);

        jMenuProgramas.setText("Programas");

        jMenuItemCrearPrograma.setText("Crear programa de formación");
        jMenuProgramas.add(jMenuItemCrearPrograma);

        jMenuItemAddCursoProg.setText("Agregar curso a programa");
        jMenuProgramas.add(jMenuItemAddCursoProg);

        jMenuItemConsProg.setText("Consulta de programa");
        jMenuProgramas.add(jMenuItemConsProg);

        jMenuBar2.add(jMenuProgramas);

        jMenuInstitutos.setText("Institutos");

        jMenuItemAltaInst.setText("Alta instituto");
        jMenuInstitutos.add(jMenuItemAltaInst);

        jMenuBar2.add(jMenuInstitutos);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltaUsuarioActionPerformed
        // TODO add your handling code here:
        jInternalFrameAltaUsr.setVisible(true);
    }//GEN-LAST:event_jMenuItemAltaUsuarioActionPerformed

    private void jRadioButtonSiDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSiDocenteActionPerformed
        // TODO add your handling code here:
        jComboBoxDocInstituto.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonSiDocenteActionPerformed

    private void jRadioButtonNoDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNoDocenteActionPerformed
        // TODO add your handling code here:
        jComboBoxDocInstituto.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonNoDocenteActionPerformed

    private void jMenuItemModUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModUsuarioActionPerformed
        // TODO add your handling code here:
        jInternalFrameModUsr.setVisible(true);
    }//GEN-LAST:event_jMenuItemModUsuarioActionPerformed

    private void jButtonCancAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancAltaActionPerformed
        // TODO add your handling code here:
        jInternalFrameAltaUsr.setVisible(false);
    }//GEN-LAST:event_jButtonCancAltaActionPerformed

    private void jButtonCancModUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancModUsrActionPerformed
        // TODO add your handling code here:
        jInternalFrameModUsr.setVisible(false);
    }//GEN-LAST:event_jButtonCancModUsrActionPerformed

    private void jMenuItemConsultaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaUsuarioActionPerformed
        // TODO add your handling code here:
        jInternalFrameConsUsr.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaUsuarioActionPerformed

    private void jButtonConUsrSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConUsrSalirActionPerformed
        // TODO add your handling code here:
        jInternalFrameConsUsr.setVisible(false);
    }//GEN-LAST:event_jButtonConUsrSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupEsDocente;
    private javax.swing.JButton jButtonCancAlta;
    private javax.swing.JButton jButtonCancModUsr;
    private javax.swing.JButton jButtonConUsrSalir;
    private javax.swing.JButton jButtonConfAlta;
    private javax.swing.JButton jButtonConfModUsr;
    private javax.swing.JComboBox<String> jComboBoxConsUsrCursos;
    private javax.swing.JComboBox<String> jComboBoxConsUsrEd;
    private javax.swing.JComboBox<String> jComboBoxConsUsrList;
    private javax.swing.JComboBox<String> jComboBoxConsUsrProg;
    private javax.swing.JComboBox<String> jComboBoxDocInstituto;
    private javax.swing.JComboBox<String> jComboBoxListaUsr;
    private javax.swing.JInternalFrame jInternalFrameAltaUsr;
    private javax.swing.JInternalFrame jInternalFrameConsUsr;
    private javax.swing.JInternalFrame jInternalFrameModUsr;
    private javax.swing.JLabel jLabel1ConsUsrNom;
    private javax.swing.JLabel jLabel1DocInst;
    private javax.swing.JLabel jLabelApellUsr;
    private javax.swing.JLabel jLabelConsUsrAp;
    private javax.swing.JLabel jLabelConsUsrCurso;
    private javax.swing.JLabel jLabelConsUsrEd;
    private javax.swing.JLabel jLabelConsUsrEmail;
    private javax.swing.JLabel jLabelConsUsrFechNac;
    private javax.swing.JLabel jLabelConsUsrNick;
    private javax.swing.JLabel jLabelConsUsrProg;
    private javax.swing.JLabel jLabelDocente;
    private javax.swing.JLabel jLabelEmailUsr;
    private javax.swing.JLabel jLabelFechNacUsr;
    private javax.swing.JLabel jLabelModUsrAp;
    private javax.swing.JLabel jLabelModUsrEmail;
    private javax.swing.JLabel jLabelModUsrNac;
    private javax.swing.JLabel jLabelModUsrNom;
    private javax.swing.JLabel jLabelNickModUsr;
    private javax.swing.JLabel jLabelNickUsr;
    private javax.swing.JLabel jLabelNomUsu;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuCursos;
    private javax.swing.JMenu jMenuInstitutos;
    private javax.swing.JMenuItem jMenuItemAddCursoProg;
    private javax.swing.JMenuItem jMenuItemAltaCurso;
    private javax.swing.JMenuItem jMenuItemAltaEdCurso;
    private javax.swing.JMenuItem jMenuItemAltaInst;
    private javax.swing.JMenuItem jMenuItemAltaUsuario;
    private javax.swing.JMenuItem jMenuItemConsEdCurso;
    private javax.swing.JMenuItem jMenuItemConsProg;
    private javax.swing.JMenuItem jMenuItemConsultaCurso;
    private javax.swing.JMenuItem jMenuItemConsultaUsuario;
    private javax.swing.JMenuItem jMenuItemCrearPrograma;
    private javax.swing.JMenuItem jMenuItemInscEdCurso;
    private javax.swing.JMenuItem jMenuItemModUsuario;
    private javax.swing.JMenu jMenuProgramas;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JRadioButton jRadioButtonNoDocente;
    private javax.swing.JRadioButton jRadioButtonSiDocente;
    private javax.swing.JSpinner jSpinnerModUsrAnioNac;
    private javax.swing.JSpinner jSpinnerModUsrDiaNc;
    private javax.swing.JSpinner jSpinnerModUsrMesNac;
    private javax.swing.JSpinner jSpinnerNacAnioUsr;
    private javax.swing.JSpinner jSpinnerNacDiaUsr;
    private javax.swing.JSpinner jSpinnerNacMesUsr;
    private javax.swing.JTextField jTextFieldApellUsuario;
    private javax.swing.JTextField jTextFieldConsUsrAp;
    private javax.swing.JTextField jTextFieldConsUsrEmail;
    private javax.swing.JTextField jTextFieldConsUsrFechNac;
    private javax.swing.JTextField jTextFieldConsUsrNom;
    private javax.swing.JTextField jTextFieldEmailUsr;
    private javax.swing.JTextField jTextFieldModUsrAp;
    private javax.swing.JTextField jTextFieldModUsrEmail;
    private javax.swing.JTextField jTextFieldModUsrNom;
    private javax.swing.JTextField jTextFieldNickUsr;
    private javax.swing.JTextField jTextFieldNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
